version: '3'

services:
  mongo:
    build: ./Mongo
    image: tanapongp/mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: mydb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - back
    container_name: database

  mongo-express:
    build: ./MongoExpress
    image: tanapongp/mongo-express:latest
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    ports:
      - "8081:8081"
    networks:
      - back
    container_name: database-interface
  server:
    build: ./Server
    image: tanapongp/python-server:lastest
    ports:
      - "8085:80"
    networks:
      - front
      - back
    container_name: server
  website:
    build: ./Web
    image: tanapongp/website:lastest
    ports:
      - "3000:3000"
    networks:
      - front
    container_name: website
networks:
  back:
  front: