version: '3'

services:
  server:
    build: ./Server
    image: tanapongp/python-server:lastest
    ports:
      - "8085:80"
    networks:
      - front
      - back
    container_name: server
  website:
    build: ./Web
    image: tanapongp/website:lastest
    ports:
      - "3000:3000"
    networks:
      - front
    container_name: website
networks:
  back:
  front: